on: [push, pull_request]
name: chrome-discord-bridge
jobs:
  go:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup-go
      uses: actions/setup-go@v5
      with:
        go-version: 1.17.x
    - uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: test
      run: go test ./...
    - name: vet
      run: go vet ./...
  assets:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup-node
      uses: actions/setup-node@v4
    - name: eslint
      run: |
        cd assets/host-test && npx -y eslint@^8.8.0 .
